@startuml
class CategoryController {
  - categoryLabel: Label
  - categoryBox: AnchorPane
  + CategoryController():
  + applyCategoryStyles(Category): void
  + addCategoryDataToCategory(Category): void
}
@enduml