@startuml
class TransactionController {
  - transactionPane: Pane
  - transactionDate: Text
  - transactionAmount: Text
  - transactionCategory: Text
  + TransactionController():
  + addTransactionDataToTransaction(Transaction): void
  - applyBorderColor(TransactionType): void
  - formatTransactionAmountText(TransactionType): void
  - setTransactionAmount(TransactionType, Double): void
  - setTransactionDate(LocalDate): void
  - setTransactionCategory(Category): void
  - applyTextColor(TransactionType): void
}
@enduml