@startuml
class CategoryListItemController {
  - onDeleteCategory: Consumer<Category>
  - categoryListItemDelete: Button
  - category: Category
  - categoryListItemContainer: HBox
  + CategoryListItemController():
  + addCategoryDataToCategoryListItem(Category): void
  + onCategoryDeleteButtonClicked(): void
  + setOnDeleteCategory(Consumer<Category>): void
}
@enduml