@startuml

class Transaction {
    +id: int {readonly}
    +title: String {readonly}
    +transaction_date: DateTime {readonly}
    +amount: double {readonly}
    +isIncome: boolean {readonly}
    +category: Category {readonly}
}

@enduml