@startuml

class ViewFactory {
    +dashboardView: AnchorPane
    +transactionView: AnchorPane
    +categoryView: AnchorPane
    +selectedView: ObjectProperty<SidebarOption> {readonly}

    +getSelectedView(): ObjectProperty<SidebarOption>
    +getDashboardView(): AnchorPane
    +getCategoryView(): AnchorPane
    +getTransactionView(): AnchorPane
    +closeStage(Stage stage): void
    +showWelcomeView(): void
    +showMainView(): void
    -createStage(FXMLLoader fxmlLoader): void
}

@enduml