@startuml

AddNewCategoryWidgetController -|> WidgetController
AddNewEntryWidgetController -|> WidgetController
BalanceStatsWidgetController -|> WidgetController
CategoriesChartWidgetController -|> WidgetController
CategoriesListWidgetController -|> WidgetController
TransactionsListWidgetController -|> WidgetController
WeeklySavingsOverviewWidgetController -|> WidgetController
RecentTransactionsWidgetController -|> WidgetController

AppViewController -|> ViewController
LoginViewController -|> ViewController
SignUpViewController -|> ViewController
WelcomeViewController -|> ViewController

ControllerFactory --> WidgetController
ControllerFactory --> ViewController

WidgetController --> Model
ViewController --> ControllerFactory

TransactionListItemController ..> Transaction
CategoryListItemController ..> Category

Model --> Transaction
Model --> Category
Model --> DatabaseManager
Model ..> SignUpToken
Model ..> LoginToken

App --> Model

AddNewCategoryWidgetController ..> AddNewCategoryWidgetFX
AddNewEntryWidgetController ..> AddNewEntryWidgetFX
BalanceStatsWidgetController ..> BalanceStatsWidgetFX
CategoriesChartWidgetController ..> CategoriesChartWidgetFX
CategoriesListWidgetController ..> CategoriesWidgetFX



TransactionsListWidgetController ..> TransactionsWidgetFX
TransactionsListWidgetController ..> TransactionListItemController
TransactionsWidgetFX ..> TransactionListItemFX


WeeklySavingsOverviewWidgetController ..> WeeklySavingsOverviewWidgetFX

CategoryController ..> CategoryFX
TransactionController ..> TransactionFX

ModalController ..> ModalFX

CategoryListItemController ..> CategoryListItemFX
CategoryListItemController ..> CategoryController
CategoryListItemController ..> CategoryFX
TransactionListItemController ..> TransactionListItemFX
TransactionListItemController ..> TransactionController
TransactionListItemController ..> TransactionWideFX

AppViewController ..> CategoriesViewFX
AppViewController ..> DashboardViewFX
AppViewController ..> TransactionsViewFX
AppViewController ..> MenubarFX

SignUpViewController ..> SignUpViewFX
LoginViewController ..> LoginViewFX
WelcomeViewController ..> WelcomeViewFX

CategoriesViewFX ..> MenubarFX
CategoriesViewFX ..> CategoriesWidgetFX
CategoriesViewFX ..> AddNewCategoryWidgetFX
CategoriesViewFX ..> CategoriesChartWidgetFX

DashboardViewFX ..> MenubarFX
DashboardViewFX ..> BalanceStatsWidgetFX
DashboardViewFX ..> RecentTransactionsWidgetFX
DashboardViewFX ..> AddNewEntryWidgetFX
DashboardViewFX ..> WeeklySavingsOverviewWidgetFX

TransactionsViewFX ..> MenubarFX
TransactionsViewFX ..> TransactionsWidgetFX

RecentTransactionsWidgetController ..> RecentTransactionsWidgetFX
RecentTransactionsWidgetFX ..> TransactionFX




@enduml