@startuml
class AddNewEntryWidgetController {
  - amountTextField: TextField
  - transactionDatePicker: DatePicker
  - categoryChoiceBox: ChoiceBox<String>
  - transactionTypeChoiceBox: ChoiceBox<String>
  - widgetGroup: Group
  - addNewEntryButton: Button
  + AddNewEntryWidgetController(Model):
  + onAddNewEntryButtonClicked(): void
  + initialize(URL, ResourceBundle): void
  - initializeCategoryChoiceBox(): void
  - initializeTransactionTypeChoiceBox(): void
  - showInvalidTransactionErrorModal(): void
  - setupDatePickerFormat(): void
  - getTransactionCategory(): Category
  - clearFormElements(): void
  - getCategorieNames(): List<String>
  - getTransactionDate(): LocalDate
  - getTransactionAmount(): double
  - getTransactionType(): TransactionType
  - clearChoiceBoxes(): void
  - updateCategories(): void
}
@enduml