@startuml
class BalanceStatsWidgetController {
  - expensesLabel: Label
  - widgetGroup: Group
  - incomeLabel: Label
  - incomeAmount: Text
  - expensesAmount: Text
  + BalanceStatsWidgetController(Model):
  + initialize(URL, ResourceBundle): void
  - setIncomeText(double): void
  - isAmountTooLarge(double): boolean
  - updateStats(): void
  - setExpensesText(double): void
}
@enduml