@startuml
class ControllerFactory {
    - widgetControllerMap: Map<String, WidgetController>
    - viewControllerMap: Map<String, ViewController>
    - model: Model
    - initializeWidgetControllerMap(Model): void
    - setLoginViewFunction(): void
    - setLogoutViewFunction(): void
    - setSignUpViewFunction(): void
    - initializeViewControllerMap(Stage): void
    + ControllerFactory(Stage, Model):
    + call(Class<?>): Object
}
@enduml