@startuml
class WelcomeViewController {
  - signUpButton: Button
  - loginButton: Button
  + WelcomeViewController(Stage, ControllerFactory):
  + onLoginButtonClicked(): void
  + onSignUpButtonClicked(): void
}
@enduml