@startuml

class CategoryController {
    +category_listview: ListView<Category>
    +new_category_title_textfield: TextField
    +new_category_color_colorpicker: ColorPicker
    +add_new_category: Button

    +initialize(): void
    +addNewCategory(): void
    +deleteCategory(int id): void
}

@enduml