@startuml

class DashboardController {
    +expense_label: Label
    +income_label: Label
    +line_chart: LineChart
    +recent_transaction_listview: ListView<Transaction>
    +new_entry_is_income_checkbox: Checkbox
    +new_entry_is_title_textfield: TextField
    +new_entry_is_amount_textfield: TextField
    +new_entry_category_combobox: Combobox
    +add_new_entry_button: Button

    +initialize(location: URL, resource: ResourceBundle): void
    +addNewEntry(): void
}


@enduml