@startuml
class DatabaseManager {
  - DATABASE_URL: String
  - connection: Connection
  - initDatabase(): void
  + DatabaseManager():
  + getAllTransactions(int): List<Transaction>
  + getUserByUsername(String): User
  + getUserById(int): User
  + getAllCategories(int): Set<Category>
  + addNewUser(String, String, String): int
  + addCategory(int, String, Color): int
  + addTransaction(int, TransactionType, double, LocalDate, Category): int
  + removeCategory(int, int): int
  + removeTransaction(int, int): int
}
@enduml