@startuml
entity SignUpToken << record >> {
    + SignUpViewController(Stage, ControllerFactory):
    - password: TextField
    - email: TextField
    - username: TextField
    - onSignUp: Function<SignUpToken, Boolean>
    - loginLink: Hyperlink
    - signUpButton: Button
    + setSignUpFunction(Function<SignUpToken, Boolean>): void
    + onLoginLinkClicked(): void
    + onSignUpButtonClicked(): void
}
@enduml