@startuml
entity Transaction << record >> {
  + Transaction(int, TransactionType, double, LocalDate, Category):
    - date: LocalDate
    - id: int
    - type: TransactionType
    - amount: double
    - category: Category
    + type(): TransactionType
    + amount(): double
    + date(): LocalDate
    + id(): int
    + category(): Category
    + getDate(): String
}
@enduml